[project]
name = "dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.2.0",
    "ipykernel>=6.29.5",
    "numpy>=2.2.3",
    "polars>=1.22.0",
    "pyarrow>=19.0.0",
    "streamlit>=1.42.0",
]
